### ISSUE TITLE
Is there a rails 5 sample?

### ISSUE THREAD

**Issue by retorquere** [auth0-samples/auth0-rubyonrails-api-samples#1]
I'm starting a new project and I'd rather start with rails 5 than having to migrate later.

**Comment by fungi-fungi** [comment]
Hi @retorquere, you can take a look here https://github.com/auth0-samples/auth0-rubyonrails-api-sample/issues/4 API only example using Rails 5

**Comment by retorquere** [comment]
I've gone with Sinatra, but thanks

**Comment by jimmyjames** [comment]
Closing as this issue is over two years old.
