### ISSUE TITLE
Ruby On Rails API: Seed projects hasn't .env file

### ISSUE THREAD

**Issue by HeikerAraujo** [auth0-samples/auth0-rubyonrails-api-samples#11]
The projects:
 01-authorization-rs256 doesn't include the .env file
 02-authorization-hs256 doesn't include the .env file

![image](https://user-images.githubusercontent.com/26749061/29173170-6e0b371a-7db0-11e7-92e9-8819c9c13ad4.png)

**Comment by aaguiarz** [comment]
Fixed in #13
