### ISSUE TITLE
Error during Bundle install

### ISSUE THREAD

**Issue by paulioceano** [auth0-samples/auth0-rubyonrails-api-samples#15]
When runing bundle install, an error is shown for nokogiri dependency.

It says that you need Ruby version 2.4 but I have Ruby version 2.4.2 instal
![screenshot_2](https://user-images.githubusercontent.com/15818783/33333807-438c18f8-d43e-11e7-8e9f-4f8e8c9a1387.png)

**Comment by jimmyjames** [comment]
Closing as this issue is over two years old. Please reopen or create a new issue if you are still experiencing this issue.
